<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ref_ui\**" />
    <Compile Remove="doc_extracted\**" />
    <EmbeddedResource Remove="ref_ui\**" />
    <EmbeddedResource Remove="doc_extracted\**" />
    <None Remove="ref_ui\**" />
    <None Remove="doc_extracted\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TallerToluca.BL\TallerToluca.BL.csproj" />
    <ProjectReference Include="..\TallerToluca.EN\TallerToluca.EN.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Assets\logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>